server:
  port: 8084

spring:
  application:
    name: payment-notification-service
  datasource:
    url: jdbc:mariadb://${DB_HOST:192.168.137.89}:${DB_PORT:3306}/${DB_NAME:food_ordering_db}
    username: ${DB_USERNAME:team}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

integration:
  order-service:
    base-url: http://192.168.137.1:8083
    update-status-path: /orders/{orderId}/status
    get-order-path: /orders/{orderId}
  notification:
    mode: LOG
    endpoint: http://192.168.137.126:8090/notifications

app:
  cors:
    allowed-origins:
      - http://192.168.137.89:3000
management:
  endpoints:
    web:
      exposure:
        include: health,info
  