spring.application.name=Monolith

# URL k?t n?i: jdbc:mariadb://[host]:[port]/[database_name]
spring.datasource.url=jdbc:mariadb://localhost:3306/food_delivery_db
spring.datasource.username=root
spring.datasource.password=sapassword

# T? ??ng t?o b?ng d?a trên code Java (Entity)
# 'update' s? t?o b?ng m?i n?u ch?a có ho?c c?p nh?t c?u hình b?ng
spring.jpa.hibernate.ddl-auto=update

# Hi?n th? các câu l?nh SQL mà Spring th?c thi xu?ng console (?? d? debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true