services:
  mysql:
    image: mysql:8.4
    container_name: food-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_identity
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:7
    container_name: food-mongo
    ports:
      - "27017:27017"

  register-service:
    build:
      context: ./register-service
    container_name: register-service
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/food_identity?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy

  login-service:
    build:
      context: ./login-service
    container_name: login-service
    ports:
      - "8082:8082"
    environment:
      MONGODB_URI: mongodb://mongo:27017/food_identity_login
      REGISTER_SERVICE_URL: http://register-service:8081
      JWT_SECRET: my-super-secret-jwt-key-for-food-app-2026
      JWT_EXPIRATION_MS: 3600000
    depends_on:
      - mongo
      - register-service
