services:
  flask1:
    build: .
    container_name: bt3_flask1
    environment:
      INSTANCE_NAME: flask1
    networks:
      - lb_net

  flask2:
    build: .
    container_name: bt3_flask2
    environment:
      INSTANCE_NAME: flask2
    networks:
      - lb_net

  nginx:
    image: nginx:latest
    container_name: bt3_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask1
      - flask2
    networks:
      - lb_net

networks:
  lb_net:
    driver: bridge
