services:
  mysql:
    image: mysql:8.0
    container_name: bai10_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_persistent_data:/var/lib/mysql

volumes:
  mysql_persistent_data:
