spring.application.name=OrderService
server.port=8083

# ─── Redis – Data Grid ────────────────────────────────────────────────────────
spring.data.redis.host=192.168.1.67
spring.data.redis.port=6379
# spring.data.redis.password=  (bỏ comment nếu Redis có mật khẩu)

# ─── RabbitMQ – Messaging ─────────────────────────────────────────────────────
spring.rabbitmq.host=192.168.1.67
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ─── OpenFeign – Inventory Service ───────────────────────────────────────────
inventory.service.url=http://192.168.1.65:8084

# ─── Logging ─────────────────────────────────────────────────────────────────
logging.level.iuh.fit.edu.orderservice=DEBUG
