spring.application.name=booking-service
server.port=8083

# ===== Database =====
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/movie_ticket_db?useUnicode=true&characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:12345}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== RabbitMQ =====
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# ===== Event-driven messaging =====
app.rabbitmq.exchange=movie.booking.events
app.rabbitmq.booking-created-routing-key=BOOKING_CREATED
