services:
  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - "5000:80"
    depends_on:
      - redis

  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - "5001:80"
    depends_on:
      - db

  worker:
    image: dockersamples/examplevotingapp_worker
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
