spring:
  application:
    name: movie-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mariadb://192.168.137.13:3306/movie_ticket_db
    username: team
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        boot:
          allow_jdbc_metadata_access: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

server:
  port: 8082

app:
  cors:
    allowed-origins: http://192.168.137.167:8085
  aws:
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
    region: ${AWS_REGION:ap-southeast-1}
    s3:
      bucket-name: ${S3_BUCKET:}
      poster-prefix: ${S3_POSTER_PREFIX:}
      public-base-url: ${S3_PUBLIC_BASE_URL:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
